### ISSUE TITLE
Unable to have multiple roles

### ISSUE THREAD

**Issue by merpac** [antialiasis/favorite-picker#10]
I'm almost certain this is my fault, but I have been unable to assign multiple roles to each item. I tried using the code listed in the previous issue, but when I do, the items don't appear at all on the page.
[Ace Attorney Picker.txt](https://github.com/antialiasis/favorite-picker/files/4806196/Ace.Attorney.Picker.txt)

**Comment by antialiasis** [comment]
The item.games.some line (which should be item.game.some, since the property on the items is called game and not games!) should be within a shouldIncludeItem function. Like so:

```
    shouldIncludeItem: function(item, settings) {
        return item.game.some(function(game){
            return settings.games.indexOf(game) !== -1; 
        })
    }
```

**Comment by merpac** [comment]
Okay, I tried it and it almost seems to work, however, the picker just says there are no items that match the criteria. I'm sorry if this has a really basic answer, I'm new to coding and I'm just doing this for fun, really.
[Ace Attorney Picker.txt](https://github.com/antialiasis/favorite-picker/files/4809930/Ace.Attorney.Picker.txt)

**Comment by antialiasis** [comment]
Ah, hello, I'm sorry I missed your response! Are you still having trouble or did you figure it out?

**Comment by merpac** [comment]
Ah, unfortunately, I didn't. Coding is really not my strong suit.

**Comment by antialiasis** [comment]
It looks like all you have to fix is on line 282, the setting is called 'game' but should be 'games' (since that's what you called the game list under the defaultSettings). If you fix that it should work!
