### ISSUE TITLE
Opening the HTML file in chrome isn't working

### ISSUE THREAD

**Issue by DiamondTheHedgehog** [antialiasis/favorite-picker#16]
So I got the code and added a couple of characters, so I wanted to preview it to make sure it worked. But when I open it up in Chrome, it just brings me to Github and shows me the source code instead. I tried opening the file in wordpress, but that just didn't work at all. Someone help please.

**Comment by antialiasis** [comment]
It sounds like the way you saved the file was using something like the "Save Page As..." function in your browser while viewing the file on GitHub. That's not the way to do it! You want to either clone the repository to your computer, click the "Raw" button near the top right of the source code page and then save _that_, or simply copy-paste the text of the file.
