### ISSUE TITLE
Getting the code to work on wordpress

### ISSUE THREAD

**Issue by DiamondTheHedgehog** [antialiasis/favorite-picker#17]
When I attempted to upload the files to Wordpress to see if it would work, this is what happened.

https://favoriteservant.com/11-2/

**Comment by antialiasis** [comment]
I'm not very familiar with Wordpress myself, but Googling for how to upload custom HTML content to Wordpress, I get stuff like this: https://blog.hubspot.com/website/upload-html-file-to-wordpress

**Comment by DiamondTheHedgehog** [comment]
So I consulted the wordpress support and apparently I couldn't make the site work without upgrading my plan, so I decided to just cancel my subscription. Do you have any suggestions for a service I could use instead?

**Comment by antialiasis** [comment]
https://neocities.org/ provides free hosting for simple webpages, which should work fine for the picker! Of course, it depends what else you might want to put on the site.
