### ISSUE TITLE
Not getting the choices?

### ISSUE THREAD

**Issue by oculusdrake** [antialiasis/favorite-picker#22]
Hello,

I don't know if I'm reading this wrong somehow, but for some reason, when I try to make a favorite picker, it just doesn't work.

Here's what I have changed from the base html, as instructed:
https://i.gyazo.com/651f76d7c1ad03fde115a5a6339f5541.png

And here's what shows up.

https://i.gyazo.com/cd03ba6ba16ba78dc0ef04b0ed193080.png

Any idea what I'm doing wrong?

**Comment by antialiasis** [comment]
You've left out the \ in front of the apostrophe in "The Dragon's Neck" - that's probably it.
