### ISSUE TITLE
Characters not appearing

### ISSUE THREAD

**Issue by Bluebellshade56** [antialiasis/favorite-picker#24]
I'm new to code, so this may be a stupid complaint, but when I view the picker, none of the characters show up.
Here's the code: 
 
    {id: 'Tansysong'},
    {id: 'Moonfall'}

This is a test code before I add all the characters, so I only used two. Can you tell me what I did wrong?

**Comment by antialiasis** [comment]
If I just insert those items into the unchanged sample file it works fine. Are you sure you changed nothing other than add those two lines where the "Define your items here" comment is? If you're not sure, try showing me the entire picker.html file.

**Comment by Bluebellshade56** [comment]
Here's the file:
[Toph favorites.zip](https://github.com/antialiasis/favorite-picker/files/11992429/Toph.favorites.zip)

**Comment by antialiasis** [comment]
Hmm, it looks like your items aren't in that picker.html file at all, and if I add them, once again they do show up. Did you inadvertently put them in the wrong file somewhere, maybe?

**Comment by Bluebellshade56** [comment]
I think I did manage to place them in the wrong file, tysm for the help! I got it to work.

**Comment by Bluebellshade56** [comment]
Ok, so that worked for some time; but when I added more characters it stopped working. Here's the file (again): 
[Toph.zip](https://github.com/antialiasis/favorite-picker/files/11995173/Toph.zip)

**Comment by antialiasis** [comment]
You've got two little problems there. First:
```
    {Id: 'Saffronstep'},
```
There's a capital I in "Id" there, but it should be lowercase.

Second:
```
    {id: 'Cottonstar(WC)'}
```
You're missing a comma at the end of this line. If you fix those two things, it should work!

**Comment by Bluebellshade56** [comment]
Ok, it's working now! Thank you so much, it really means a lot that you took the time out of your day to help me with this.
