### ISSUE TITLE
Choices not appearing

### ISSUE THREAD

**Issue by Jellyflower22** [antialiasis/favorite-picker#25]
idk what i did wrong but when i go on the website everything's there except the choices :/

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0">
<title>Taylor Swift songs Favorite Picker</title>
<link rel="shortcut icon" type="image/jpg" href="ts.jpg"/>
<style>
body {
    background:#FFF;
    color:#000;
    font-family:verdana, sans-serif;
    font-size:10pt;
    margin:0;
    padding:10px;
}
 
a:link, a:visited {
    color:#008;
    font-weight:bold;
    text-decoration:none;
}
 
a:active, a:hover {
    color:#ACF;
}
 
.info {
    font-weight:bold;
}
 
button {
    font-family:inherit;
    cursor:pointer;
    border:0;
    border-radius:3px;
    padding:0.3em 0.5em;
    background:#CCC;
    color:#000;
}
 
button:hover {
    background:#DDD;
}
 
button.disabled {
    background:#DDD;
    color:#888;
    cursor:not-allowed;
}
 
button.disabled:hover {
    background:#DDD;
}
 
#container {
    position:relative;
    margin-left:-10px;
    margin-right:-10px;
    padding:10px;
    overflow:hidden;
}
 
@media (min-width:1024px) {
    /* Put the found favorites beside the picking div when the window is sufficiently large */
    #picking {
        float:left;
        width:636px;
    }
 
    #secondary {
        margin-left:646px;
    }
}
 
@media (min-width:1300px) {
    /* Once we get to the point where 636px is less than half of the width of the screen, make the picking div just take up half */
    #picking {
        width:50%;
    }
 
    #secondary {
        margin-left:51%;
    }
}
 
#pick {
    background:#58F;
    color:#FFF;
    font-size:larger;
    font-weight:bold;
    width:6em;
    border-radius:5px;
    margin-right:10px;
}
 
#pick.disabled {
    background:#ACF;
}
 
#pick:hover {
    background:#ACF;
}
 
.item-list li {
    margin:5px;
    display:inline-block;
    padding:0;
    text-align:center;
    position: relative;
    vertical-align:top;
    line-height:1.2px;
    width:106px;
}
 
.item-list li .name {
    line-height:1.2;
}
 
.item-list li .image {
    display:inline-block;
    height:106px;
    width:106px;
    background:#F7F7F7;
    border-radius:50%;
    z-index:1;
    position:relative;
    overflow:hidden;
}
 
.item-list li img {
    vertical-align:middle;
    max-height:100%;
    max-width:100%;
}
 
.item-list li .image span {
    padding:0;
    border:3px solid transparent;
    height:100px;
    width:100px;
}
 
.item-list li span {
    display:inline-block;
    vertical-align:middle;
    line-height:1.2;
}
 
.item-list li.selected .image span {
    padding:0;
    height:100px;
    width:100px;
    border:3px solid #7AC;
    border-radius:100%;
}
 
.item-list li:hover .image {
    background:#CDF;
}
 
.item-list.sorting li:hover .image {
    background:#F7F7F7;
}
 
@media (max-width:636px) {
    .item-list {
        line-height:10px;
        padding;0;
    }
 
    .item-list li {
        line-height:10px;
        height:75px;
        width:75px;
    }

    .item-list li .image {
        height:81px;
        width:81px;
    }

    .item-list li .image span, .item-list li.selected .image span {
        height:75px;
        width:75px;
    }
}
 
@media (max-width:423px) {
    .item-list {
        line-height:10px;
        padding;0;
    }
 
    .item-list li {
        line-height:10px;
        height:125px;
        width:75px;
    }

    .item-list li .image {
        height:56px;
        width:56px;
    }

    .item-list li .image span, .item-list li.selected .image span  {
        height:50px;
        width:50px;
    }
}
 
#evaluating li {
    cursor:pointer;
}
 
#favorites li {
    cursor:move;
}
 
#evaluating, #buttons {
    text-align:center;
    margin:auto;
}
 
#evaluating li.notice {
    width:auto;
    height:auto;
    max-width:260px;
    margin:auto;
    background:#F7F7F7;
    border-radius:10px;
    padding:30px 30px;
    color:#000;
    text-align:center;
    line-height:1.4;
    cursor:auto;
    font-size:10pt;
}
 
#buttons {
    margin-top:30px;
    position:relative;
    z-index:3;
}
</style>
</head>
<body>
<h1>Taylor Swift songs Favorite Picker</h1>
<p>For each group of Taylor Swift songs presented to you, click one or more of your favorites from that group and press the "Pick" button. Eventually, your favorite songs will start appearing under "Found Favorites". You can continue as long as you like to construct an arbitrarily long list of your favorite songs!</P>
<p>In principle, this picker is perfectly accurate, provided you pick consistently - you'll correctly get your second favorite second, even if it's pitted against your absolute favorite early on, for instance. You can reorder your favorites after you've found them, but in principle you shouldn't need to.</P>
<p>Feel free to include or exclude certain albums based on what you've listened to!<sup>(Songs outside of albums are not yet included but will most likely be one day.)</sup></p>
<p>Original source code by <a href="https://twitter.com/antialiasis">antialiasis</a> with instructions <a href="https://github.com/antialiasis/favorite-picker">here,</a> based off of the <a href="https://www.dragonflycave.com/favorite.html">Favorite Pokemon Picker!</a> and the <a href="https://wcpicker.neocities.org/picker">Warrior Cats Favorite Picker!</a></p>
<p>Include albums:
<label><input type="checkbox" name="roles" class="roles" value="tay"> Taylor Swift</label>
<label><input type="checkbox" name="roles" class="roles" value="fea"> Fearless</label>
<label><input type="checkbox" name="roles" class="roles" value="spe"> Speak Now</label>
<label><input type="checkbox" name="roles" class="roles" value="red"> Red</label>
<label><input type="checkbox" name="roles" class="roles" value="nin"> 1989</label>
<label><input type="checkbox" name="roles" class="roles" value="rep"> reputation</label>
<label><input type="checkbox" name="roles" class="roles" value="lov"> Lover</label>
<label><input type="checkbox" name="roles" class="roles" value="fol"> folklore</label>
<label><input type="checkbox" name="roles" class="roles" value="eve"> evermore</label>
<label><input type="checkbox" name="roles" class="roles" value="mid"> Midnights</label>
</p>

<p>Number of characters displayed:
<input type="number" id="max-batch-size">
 
<div id="container">
 
<div id="picking">
<ul id="evaluating" class="item-list">
</ul>
 
<p id="buttons"><button id="pick">Pick</button> <button id="pass">Pass</button> <button id="undo">Undo</button> <button id="redo">Redo</button> <button id="reset">Reset</button></p>

</div>
 
<div id="secondary">
<h2>Found favorites</h2>
 
<ol id="favorites" class="item-list">
</ol>
</div>
</div>
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="picker.js"></script>
<script src="picker-ui.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sortablejs@1.7.0/Sortable.min.js"></script>
<script>
'use strict';
 
var items = [
      // Taylor Swift
    {id: 'timmcgraw', name: 'Tim McGraw', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'picturetoburn', name: 'Picture To Burn', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'teardropsonmyguitar', name: 'Teardrops On My Guitar', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'aplaceinthisworld', name: 'A Place In This World', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'coldasyou', name: 'Cold As You', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'theoutside', name: 'The Outside', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'tiedtogetherwithasmile', name: 'Tied Together With A Smile', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'staybeautiful', name: 'Stay Beautiful', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'shouldvesaidno', name: 'Should\'ve Said No', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'maryssong', name: 'Mary\'s Song (Oh My My My)', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'oursong', name: 'Our Song', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'imonlymewhenimwithyou', name: 'I\'m Only Me When I\'m With You', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'invisible', name: 'Invisible', image: 'Taylor Swift.png', role: 'tay', recurring: true},
    {id: 'aperfectlygoodheart', name: 'A Perfectly Good Heart', image: 'Taylor Swift.png', role: 'tay', recurring: true},
      // Fearless
    {id: 'fearless', name: 'Fearless', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'fifteen', name: 'Fifteen', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'lovestory', name: 'Love Story', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'heystephen', name: 'Hey Stephen', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'whitehorse', name: 'White Horse', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'youbelongwithme', name: 'You Belong With Me', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'breathe', name: 'Breathe', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'tellmewhy', name: 'Tell Me Why', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'yourenotsorry', name: 'You\'re Not Sorry', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'thewayilovedyou', name: 'The Way I Loved You', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'foreveralways', name: 'Forever & Always', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'thebestday', name: 'The Best Day', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'change', name: 'Change', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'jumpthenfall', name: 'Jump Then Fall', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'untouchable', name: 'Untouchable', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'fapiano', name: 'Forever & Always (Piano Version)', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'comeinwiththerain', name: 'Come In With The Rain', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'superstar', name: 'Superstar', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'theothersideofthedoor', name: 'The Other Side Of The Door', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'todaywasafairytale', name: 'Today Was A Fairytale', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'youalloverme', name: 'You All Over Me', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'mrperfectlyfine', name: 'Mr. Perfectly Fine', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'wewerehappy', name: 'We Were Happy', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'thatswhen', name: 'That\'s When', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'dontyou', name: 'Don\'t You', image: 'Fearless.png', role: 'fea', recurring: true},
    {id: 'byebyebaby', name: 'Bye Bye Baby', image: 'Fearless.png', role: 'fea', recurring: true},
      // Speak Now
    {id: 'mine', name: 'Mine', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'sparksfly', name: 'Sparks Fly', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'backtodecember', name: 'Back To December', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'speaknow', name: 'Speak Now', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'dearjohn', name: 'Dear John', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'mean', name: 'Mean', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'thestoryofus', name: 'The Story Of Us', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'nevergrowup', name: 'Never Grow Up', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'enchanted', name: 'Enchanted', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'betterthanrevenge', name: 'Better Than Revenge', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'innocent', name: 'Innocent', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'haunted', name: 'Haunted', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'lastkiss', name: 'Last Kiss', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'longlive', name: 'Long Live', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'ours', name: 'Ours', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'superman', name: 'Superman', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'electrictouch', name: 'Electric Touch', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'whenemmafallsinlove', name: 'When Emma Falls In Love', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'icanseeyou', name: 'I Can See You', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'castlescrumbling', name: 'Castles Crumbling', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'foolishone', name: 'Foolish One', image: 'Speak Now.png', role: 'spe', recurring: true},
    {id: 'timeless', name: 'Timeless', image: 'Speak Now.png', role: 'spe', recurring: true},
      // Red
    {id: 'stateofgrace', name: 'State Of Grace', image: 'Red.png', role: 'red', recurring: true},
    {id: 'red', name: 'Red', image: 'Red.png', role: 'red', recurring: true},
    {id: 'treacherous', name: 'Treacherous', image: 'Red.png', role: 'red', recurring: true},
    {id: 'iknewyouweretrouble', name: 'I Knew You Were Trouble', image: 'Red.png', role: 'red', recurring: true},
    {id: 'alltoowell', name: 'All Too Well', image: 'Red.png', role: 'red', recurring: true},
    {id: 'twentytwo', name: '22', image: 'Red.png', role: 'red', recurring: true},
    {id: 'ialmostdo', name: 'I Almost Do', image: 'Red.png', role: 'red', recurring: true},
    {id: 'weareneverevergettingbacktogether', name: 'We Are Never Ever Getting Back Together', image: 'Red.png', role: 'red', recurring: true},
    {id: 'staystaystay', name: 'Stay Stay Stay', image: 'Red.png', role: 'red', recurring: true},
    {id: 'thelasttime', name: 'The Last Time', image: 'Red.png', role: 'red', recurring: true},
    {id: 'holyground', name: 'Holy Ground', image: 'Red.png', role: 'red', recurring: true},
    {id: 'sadbeautifultragic', name: 'Sad Beautiful Tragic', image: 'Red.png', role: 'red', recurring: true},
    {id: 'theluckyone', name: 'The Lucky One', image: 'Red.png', role: 'red', recurring: true},
    {id: 'everythinghaschanged', name: 'Everything Has Changed', image: 'Red.png', role: 'red', recurring: true},
    {id: 'starlight', name: 'Starlight', image: 'Red.png', role: 'red', recurring: true},
    {id: 'beginagain', name: 'Begin Again', image: 'Red.png', role: 'red', recurring: true},
    {id: 'themomentiknew', name: 'The Moment I Knew', image: 'Red.png', role: 'red', recurring: true},
    {id: 'comebackbehere', name: 'Come Back...Be Here', image: 'Red.png', role: 'red', recurring: true},
    {id: 'girlathome', name: 'Girl At Home', image: 'Red.png', role: 'red', recurring: true},
    {id: 'sogacoustic', name: 'State Of Grace (Acoustic Version)', image: 'Red.png', role: 'red', recurring: true},
    {id: 'ronan', name: 'Ronan', image: 'Red.png', role: 'red', recurring: true},
    {id: 'betterman', name: 'Better Man', image: 'Red.png', role: 'red', recurring: true},
    {id: 'nothingnew', name: 'Nothing New', image: 'Red.png', role: 'red', recurring: true},
    {id: 'babe', name: 'Babe', image: 'Red.png', role: 'red', recurring: true},
    {id: 'messageinabottle', name: 'Message In The World', image: 'Red.png', role: 'red', recurring: true},
    {id: 'ibetyouthinkaboutme', name: 'I Bet You Think About Me', image: 'Red.png', role: 'red', recurring: true},
    {id: 'foreverwinter', name: 'Forever Winter', image: 'Red.png', role: 'red', recurring: true},
    {id: 'run', name: 'Run', image: 'Red.png', role: 'red', recurring: true},
    {id: 'theveryfirstnight', name: 'The Very First Night', image: 'Red.png', role: 'red', recurring: true},
    {id: 'atwtmvtvftv', name: 'All Too Well (10 Minute Version)', image: 'Red.png', role: 'red', recurring: true},
      // 1989
    {id: 'welcometonewyork', name: 'Welcome To New York', image: '1989.png', role: 'nin', recurring: true},
    {id: 'blankspace', name: 'Blank Space', image: '1989.png', role: 'nin', recurring: true},
    {id: 'style', name: 'Style', image: '1989.png', role: 'nin', recurring: true},
    {id: 'outofthewoods', name: 'Out Of The Woods', image: '1989.png', role: 'nin', recurring: true},
    {id: 'allyouhadtodowasstay', name: 'All You Had To Do Was Stay', image: '1989.png', role: 'nin', recurring: true},
    {id: 'shakeitoff', name: 'Shake It Off', image: '1989.png', role: 'nin', recurring: true},
    {id: 'iwishyouwould', name: 'I Wish You Would', image: '1989.png', role: 'nin', recurring: true},
    {id: 'badblood', name: 'Bad Blood', image: '1989.png', role: 'nin', recurring: true},
    {id: 'wildestdreams', name: 'Wildest Dreams', image: '1989.png', role: 'nin', recurring: true},
    {id: 'howyougetthegirl', name: 'How You Get The Girl', image: '1989.png', role: 'nin', recurring: true},
    {id: 'thislove', name: 'This Love', image: '1989.png', role: 'nin', recurring: true},
    {id: 'iknowplaces', name: 'I Know Places', image: '1989.png', role: 'nin', recurring: true},
    {id: 'clean', name: 'Clean', image: '1989.png', role: 'nin', recurring: true},
    {id: 'wonderland', name: 'Wonderland', image: '1989.png', role: 'nin', recurring: true},
    {id: 'youareinlove', name: 'You Are In Love', image: '1989.png', role: 'nin', recurring: true},
    {id: 'newromantics', name: 'New Romantics', image: '1989.png', role: 'nin', recurring: true},
      // reputation
    {id: 'readyforit', name: '...Ready For It?', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'endgame', name: 'End Game', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'ididsomethingbad', name: 'I Did Something Bad', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'dontblameme', name: 'Don\'t Blame Me', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'delicate', name: 'Delicate', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'lookwhatyoumademedo', name: 'Look What You Made Me Do', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'soitgoes', name: 'So It Goes...', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'gorgeous', name: 'Gorgeous', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'getawaycar', name: 'Getaway Car', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'kingofmyheart', name: 'King Of My Heart', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'dancingwithourhandstied', name: 'Dancing With Our Hands Tied', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'dress', name: 'dress', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'thisiswhywecanthavenicethings', name: 'This Is Why We Can\'t Have Nice Things', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'callitwhatyouwant', name: 'Call It What You Want', image: 'reputation.png', role: 'rep', recurring: true},
    {id: 'newyearsday', name: 'New Year\'s Day', image: 'reputation.png', role: 'rep', recurring: true},
      // Lover
    {id: 'iforgotthatyouexisted', name: 'I Forgot That You Existed', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'cruelsummer', name: 'Cruel Summer', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'lover', name: 'Lover', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'theman', name: 'The Man', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'thearcher', name: 'The Archer', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'ithinkheknows', name: 'I Think He Knows', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'missamericanatheheartbreakprince', name: 'Miss Americana & The Heartbreak Prince', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'paperrings', name: 'Paper Rings', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'corneliastreet', name: 'Cornelia Street', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'deathbyathousandcuts', name: 'Death By A Thousand Cuts', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'londonboy', name: 'London Boy', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'soonyoullgetbetter', name: 'Soon You\'ll Get Better', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'falsegod', name: 'False God', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'youneedtocalmdown', name: 'You Need To Calm Down', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'afterglow', name: 'Afterglow', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'me', name: 'ME!', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'itsnicetohaveafriend', name: 'It\'s Nice To Have A Friend', image: 'Lover.png', role: 'lov', recurring: true},
    {id: 'daylight', name: 'Daylight', image: 'Lover.png', role: 'lov', recurring: true},
      // folklore
    {id: 'theone', name: 'the 1', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'cardigan', name: 'cardigan', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'thelastgreatamericandynasty', name: 'the last great american dynasty', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'exile', name: 'exile', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'mytearsricochet', name: 'my tears ricochet', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'mirrorball', name: 'mirrorball', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'seven', name: 'seven', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'august', name: 'august', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'thisismetrying', name: 'this is me trying', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'illicitaffairs', name: 'illicit affairs', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'invisiblestring', name: 'invisible string', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'madwoman', name: 'mad woman', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'epiphany', name: 'epiphany', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'betty', name: 'betty', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'peace', name: 'peace', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'hoax', name: 'hoax', image: 'folklore.png', role: 'fol', recurring: true},
    {id: 'thelakes', name: 'the lakes', image: 'folklore.png', role: 'fol', recurring: true},
      // evermore
    {id: 'willow', name: 'willow', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'champagneproblems', name: 'champagne problems', image: 'evemore.png', role: 'eve', recurring: true},
    {id: 'goldrush', name: 'gold rush', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'tisthedamnseason', name: '/'tis the damn season', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'tolerateit', name: 'tolerate it', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'nobodynocrime', name: 'no body no crime', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'happiness', name: 'happiness', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'dorothea', name: 'dorothea', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'coneyisland', name: 'coney island', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'ivy', name: 'ivy', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'cowboylikeme', name: 'cowboy like me', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'longstoryshort', name: 'long story short', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'marjorie', name: 'marjorie', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'closure', name: 'closure', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'evermore', name: 'evermore', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'rightwhereyouleftme', name: 'right where you left me', image: 'evermore.png', role: 'eve', recurring: true},
    {id: 'itstimetogo', name: 'it\'s time to go', image: 'evermore.png', role: 'eve', recurring: true},
      // Midnights
    {id: 'lavenderhaze', name: 'Lavender Haze', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'maroon', name: 'Maroon', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'antihero', name: 'Anti-Hero', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'snowonthebeach', name: 'Snow On The Beach', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'youreonyourown', name: 'You\'re On Your Own', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'midnightrain', name: 'Midnight Rain', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'question', name: 'Question...?', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'vigilanteshit', name: 'Vigilante Shit', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'bejeweled', name: 'Bejeweled', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'labyrinth', name: 'Labyrinth', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'karma', name: 'Karma', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'sweetnothing', name: 'Sweet Nothing', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'mastermind', name: 'Mastermind', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'thegreatwar', name: 'The Great War', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'biggerthanthewholesky', name: 'Bigger Than The Whole Sky', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'paris', name: 'Paris', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'highinfidelity', name: 'High Infidelity', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'glitch', name: 'Glitch', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'wouldvecouldveshouldve', name: 'Would\'ve, Could\'ve, Should\'ve', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'dearreader', name: 'Dear Reader', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'hitsdifferent', name: 'Hits Different', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'yourelosingme', name: 'You\'re Losing Me', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'sotbmorelana', name: 'Snow On The Beach (feat. More Lana Del Rey)', image: 'Midnights.png', role: 'mid', recurring: true},
    {id: 'karmaicespice', name: 'Karma (feat. Ice Spice)', image: 'Midnights.png', role: 'mid', recurring: true},
];
 
var myPicker = new picker.Picker({
    items: items,
    localStorageKey: 'picker-state',
    defaultSettings: {
        minBatchSize: 2,
        maxBatchSize: 20,
        roles: ['tay', 'fea', 'spe', 'red', 'nin', 'rep', 'lov', 'fol', 'eve', 'mid'],
        recurringOnly: true
    },
    shouldIncludeItem: function(item, settings) {
        // Include only if:
        // 1. the character's role is in the list of roles we've, and
        // 2. we haven't the "recurring only" box, or the character is a recurring character.
        return settings.roles.indexOf(item.role) !== -1 && (!settings.recurringOnly || item.recurring);
    }
});
 
var pickerUI = new PickerUI(myPicker, {
    elements: {
        pick: "#pick",
        pass: "#pass",
        undo: "#undo",
        redo: "#redo",
        reset: "#reset",
        evaluating: "#evaluating",
        favorites: "#favorites",
        settings: {
          roles: '.roles',
          recurringOnly: '#recurring-only',
          maxBatchSize: '#max-batch-size',
        },
    },
    getItemElem: function(item, settings) {
        return $('<li><span class="image"><span><img src="' + item.image + '" alt="' + item.name + '" title="' + item.name + '" loading="eager"></span></span><span class="name">' + item.name + '</span></li>');
       }
});
pickerUI.initialize();
 
/* Sortable favorites - you can safely remove this, and the Sortable.min.js script, if you don't want to be able to sort your favorite list. */
var sortable = new Sortable(pickerUI.elem.favorites.get(0), {
    draggable: '.item',
    animation: 100,
    onStart: function() {
        pickerUI.elem.favorites.addClass("sorting");
    },
    onEnd: function() {
        pickerUI.elem.favorites.removeClass("sorting");
    },
    onUpdate: function() {
        myPicker.setFavorites(pickerUI.elem.favorites.children().map(function() {
            return pickerUI.getItem(this);
        }).get());
        pickerUI.update(true);
    }
});
/* End sortable favorites */
</script>
</body>
</html>

**Comment by antialiasis** [comment]
Some of these song titles have apostrophes in them. This means you need to either surround the title with double quotes ("") or escape the apostrophe in the title by writing it as \'. Note that that's a backslash, not a slash. Here I would recommend doing double quotes throughout, as none of the titles have actual double quotes, at a glance.
