### ISSUE TITLE
I've been experimenting with the examples before I start creating my own version, and I'm having difficulty with the filter

### ISSUE THREAD

**Issue by redtutel** [antialiasis/favorite-picker#4]
I'm still very new to coding, especially in this language. I can get the basic sorting to work, but when I try the code for filtering, no items appear, even though the checkboxes do. And clicking the checkboxes doesn't do anything. What should I do?

**Comment by antialiasis** [comment]
Hey! Did you figure out the error? I'm happy to help if you're still having issues.

**Comment by redtutel** [comment]
It was a copy and paste mistake on my part, embarrassingly. 

Although I would like advice as to give each option multiple roles, like say, 'lawyer' and 'male', as well as to have multiple "X only" options (like "Recurring characters only" or "One-shot characters only)

**Comment by antialiasis** [comment]
You can combine as many conditions as you like in the shouldIncludeItem function by using && (and). For example, if you want a 'One-shot characters only' checkbox in addition to 'Recurring characters only' (assuming a one-shot character is simply any character who *isn't* recurring), you can use `(!settings.recurringOnly || item.recurring) && (!settings.oneshotOnly || !item.recurring)`. Note the exclamation mark before item.recurring; that negates it.

I don't think you want multiple *roles* in that example; surely you'd want `role: 'lawyer', gender: 'male'`. But if you definitely wanted multiple roles, you'd want `roles: ['lawyer', 'defendant']`. Filtering on that is a little more complex; in modern browsers you can use `item.roles.some(function(role) { return settings.roles.indexOf(role) !== -1; })`.

Let me know if that's not clear enough and I'll give a more complete example.

**Comment by redtutel** [comment]
Your advice was very helpful, thank you.

I could use help with adding a reset button next to the "undo," "redo,", and "pass" buttons

**Comment by antialiasis** [comment]
To add a static reset button, you can simply add an HTML button with a class or ID wherever you want in the document:

    <button class="reset">Reset</button>

And then, where you define the Picker object, include `reset` under `elements`, with an appropriate selector:
    
    elements: {
        pick: "#pick",
        pass: "#pass",
        undo: "#undo",
        redo: "#redo",
        reset: ".reset",
        evaluating: "#evaluating",
        favorites: "#favorites"
    }

**Comment by redtutel** [comment]
For filtering, I'm using getFilteredItems. 

I used your advice of having more the one tag for organizing items. However, I still want to give some items multiple of the same type of tag. 


The thing I'm working on is a picker from Fire Emblem Characters. One of the things I'm organizing them on is by game, but some characters appear in multiple games. 

For example: games: [Awakening, Fates]


So how do I impliment that in getFilteredItems?

**Comment by antialiasis** [comment]
Are you sure you need getFilteredItems? Do you also have something like the example with removing duplicates?

If you do need it, in any case, then you'll want to implement the check I suggested above while looping through the items:

    if (item.games.some(function(game) { return settings.games.indexOf(game) !== -1; })) continue;

**Comment by redtutel** [comment]
I did implement a system to remove duplicates.

The current version uses this to filter:
`            if (settings.roles.indexOf(items[i].role) === -1 || settings.games.indexOf(items[i].game) === -1 || settings.Classes.indexOf(items[i].Class) === -1) continue;
`

roles, games and Classes are the main tags. 

And my current, functioning way of adding items to the list:

`    {id: 'Gangrel', name: 'Gangrel', image: 'Gangrel_Portrait.png', game: 'Awakening', Class: 'Thief', role: 'Antagonist'},
`

I tried to implement the multiple roles system in this way:
`    {id: 'Gangrel', name: 'Gangrel', image: 'Gangrel_Portrait.png', game: 'Awakening', Class: 'Thief', role: ['Antagonist', 'Ally']},
`

`            if (item.games.some(function(game) { return settings.games.indexOf(game) !== -1; }) || settings.games.indexOf(items[i].game) === -1 || settings.Classes.indexOf(items[i].Class) === -1) continue;
`

It did not work. I'm pretty sure I misinterpreted something or made a mistake, and I would like to know what that mistake was.


There is probably at least one character that needs more then one of each tag as well

**Comment by redtutel** [comment]
I finally finished it. What web hosts would you recommend?

**Comment by antialiasis** [comment]
I don't really know what's available right now in terms of simple hosting - I've got a virtual server, but you don't need anything of that scale to host a picker.

You could just use GitHub pages, though, since you're already on GitHub! There are instructions here: https://pages.github.com/

**Comment by redtutel** [comment]
It's been a long time. I've used it quit a bit now, I'd say it's a bit of an odd hobby. How to you create a counter that show how many need to be eliminated until you find the next favorite?

**Comment by antialiasis** [comment]
I did it like this:

```
    onUpdate: function(updateType) {
        var totalPokemon = this.picker.state.items.length;
        var favorites = this.picker.state.arrays.favorites.length;
        var eliminated = this.picker.state.arrays.eliminated.length;
        var remaining = Math.max(0, totalPokemon - favorites - eliminated - 1);

        $("#remaining").text(remaining);
    },
```

with a span with id="remaining" on the page where the counter should be.

**Comment by redtutel** [comment]
I admit that I gave up and am now trying again with getting the counter to work.

Do I put this code in the existing onUpdate, or do I make a new onUpdate? And do I need to work on the Javascript files to implement it?

**Comment by antialiasis** [comment]
I put this code inside the options for PickerUI in the picker HTML file - you don't need to edit the actual picker Javascript files. Like this:
```
var pickerUI = new PickerUI(myPicker, {
    elements: {
        pick: "#pick",
        pass: "#pass",
        undo: "#undo",
        redo: "#redo",
        reset: ".reset",
        evaluating: "#pokemon",
        favorites: "#favorites"
    },
    onUpdate: function(updateType) {
        var totalPokemon = this.picker.state.items.length;
        var current = this.picker.state.arrays.current.length;
        var favorites = this.picker.state.arrays.favorites.length;
        var eliminated = this.picker.state.arrays.eliminated.length;
        var evaluating = this.picker.state.arrays.evaluating.length;
        var remaining = Math.max(0, totalPokemon - favorites - eliminated - 1);

        $("#remaining").text(remaining);
    },
});

**Comment by redtutel** [comment]
I can't seem to get the number to actually appear.
Maybe I made a mistake with the HTML:

`<div class="picker-info">
                    <p>Characters remaining to be eliminated before next favorite is found: <span id="remaining"></span></p>
                </div>	`

Do I need to add #remaining to the pickerUI?

**Comment by antialiasis** [comment]
The code I gave above and the span with id="remaining" *should* be enough. If you like, you can send me your files in full and I can try to figure out what's going wrong.

**Comment by redtutel** [comment]
Here it is: https://github.com/redtutel/Fire-Emblem-Favorites-Picker/blob/master/index.html

**Comment by antialiasis** [comment]
You put the onUpdate function in the wrong place - inside the options for the sortable favorites instead of the options for PickerUI. You want it to go right after the element definitions, like in the example above.

**Comment by redtutel** [comment]
Oh man, I always get tunnel vision on the littlest things. Thank you so much. It's working now.
